# Numpy examples

Graeme Hawker, University of Strathclyde, 2018-07-23

See https://docs.scipy.org/doc/numpy/index.html

In [1]:
import numpy as np

In [2]:
# create a 1d numpy array and index
a = np.array([10,20,30,40])
a[0]

10

In [5]:
# create a couple of 2d numpy arrays
# we use the print() function as this shows the array in a readable format
a = np.array([[4, 6, 5],[3, 1, 2]])
b = np.array([[7, 8, 9]])
print(a)

[[4 6 5]
 [3 1 2]]


In [6]:
print(b)

[[7 8 9]]


In [7]:
# sorting along axes
a.sort(axis=0)
print(a)

[[3 1 2]
 [4 6 5]]


In [8]:
a.sort(axis=1)
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
# transposing
c = b.transpose()
print(c)

[[7]
 [8]
 [9]]


In [11]:
# concatenating two arrays
# what happens if you change the second argument to axis=1?
# what happens if you remove this argument altogether?
d = np.concatenate((a,b),axis=0)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# dot product of two arrays
e = np.dot(d,c)
print(e)

[[ 50]
 [122]
 [194]]


In [13]:
# calculate eigenvalues
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html
f = np.linalg.eig(d)
print(f)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [23]:
# fast fourier transform example
# https://docs.scipy.org/doc/numpy/reference/routines.fft.html
a = np.array([1., 2., 1., -1., 1.5])
b = np.fft.fft(a)
print(b)

[ 4.5       +0.j          2.08155948-1.65109876j -1.83155948+1.60822041j
 -1.83155948-1.60822041j  2.08155948+1.65109876j]


In [24]:
# lots of stats functions: https://docs.scipy.org/doc/numpy/reference/routines.statistics.html
a = np.array([[1.0, 2.0, 1.0, -1.0, 1.5],
              [3, 5, 7, 15, -5]])
print(np.median(a, axis=1))

[1. 5.]


In [25]:
# calculate frequencies and bins for histogram of flattened data
# first array returned gives frequencies, second gives bins used
print(np.histogram(a))

(array([1, 0, 1, 4, 1, 1, 1, 0, 0, 1], dtype=int64), array([-5., -3., -1.,  1.,  3.,  5.,  7.,  9., 11., 13., 15.]))
